### ISSUE TITLE
Electron Instance only shows a textarea

### ISSUE THREAD

**Issue by jasuperior** [chrispsn/mesh#36]
When I do `npm start` from the `src` directory. It starts an electron instance which only displays a textarea which I does nothing when I type text into it. I've tried typing `name` then pressing `enter` or `tab` but all it does is the default behavior.

**Comment by jasuperior** [comment]
When i pull up the dev tools, this is the error i receive:

`Uncaught SyntaxError: Unexpected token )`

**Comment by jasuperior** [comment]
I figured out what the problem was. There as a trailing comma in:

`code_editor.setSelection(
            {line: start.line - 1, ch: start.column},
            {line: end.line - 1, ch: end.column},
 );`

Dont know why that would present a problem tho

**Comment by chrispsn** [comment]
Hmm, it sounds something like ES6 syntax that' not supported in older versions of Node. Maybe try updating to the latest LTS version?

**Comment by jasuperior** [comment]
hmmm... @chrispsn you may be right. I updated my node, and all is well in the world. 

Its just strange, I've never had a problem with trailing commas before. Hasnt it been standard in javascript since like es3?

**Comment by chrispsn** [comment]
I'm pretty new to JS so am not sure - but have updated the README to clarify you need the latest LTS version of node.

Thanks for trying out Mesh! Do you have any other feedback?

**Comment by jasuperior** [comment]
Well as far as feedback. I'd say It would be cooler if the spreadsheet was already setup, i.e. excel with all the cells already laid out. Allowing me to place information into arbitrary cells and it compiling the code from a top down left-to-right fashion. 

Also, if it didnt include the mesh code in the compiled code, that would be awesome as well. The mesh code is only useful within the mesh environment, it doesnt really have any purpose if I wanted to use the compiled code for anything else though.
