### ISSUE TITLE
Putting a Uri as value of cell breaks things.

### ISSUE THREAD

**Issue by rluiten** [chrispsn/mesh#67]
Example i selected a cell pasted in `https://github.com/chrispsn/mesh`.
Hit Enter and get error in console. `VM723:4 Uncaught SyntaxError: Unexpected token :`

The code pane shows this
```javascript
'use strict';
const _CELLS = {
    A1: ({
      v: https://github.com/chrispsn/mesh,
      l: [0,0],
      n: false
    })
}
```

**Comment by chrispsn** [comment]
Thanks, just pushed a short-term fix to how regexes are matched.

Any chance you'd like to tighten it further and submit a pull request? :)

See, eg:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Advanced_searching_with_flags
